#!/bin/sh

# Helper script to launch Chromium as the user `weston` within a login shell.
# Intended to be used in weston.ini, where escaping or quoting is not supported.

export XDG_RUNTIME_DIR=/run/user/1000
export WAYLAND_DISPLAY=wayland-1

exec chromium "$@"
